### ISSUE TITLE
block

### ISSUE THREAD

**Issue by TeaqariaWTF** [CHIZI-0618/AdGuardHomeForMagisk#1]
I installed it but the ads are not blocked

**Comment by TeaqariaWTF** [comment]
![Uploading Screenshot_20211119-064950_Iceraven.png…]()

**Comment by CHIZI-0618** [comment]
> I installed it but the ads are not blocked

[This version](https://github.com/CHIZI-0618/AdGuardHomeForMagisk/releases/tag/v0.107.4) uses iptables to forward local port `53` to `AdguardHome.dns.port` to solve the problem of local use.

>         if wait_AdGuardHome_listen ; then
>            dns_port=`cat ${AdGuardHome_dir}/AdGuardHome.yaml | grep "^  port:" | cut -d ' ' -f 4`
>            ${iptables} -t nat -A OUTPUT -m owner --uid-owner 0 --gid-owner 3005 -p udp --dport 53 -j RETURN
>            ${iptables} -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports ${dns_port}
>         fi

**Comment by TeaqariaWTF** [comment]
Will you continue the project?  Will there be future updates?

**Comment by CHIZI-0618** [comment]
> Will you continue the project? Will there be future updates?

I will continue to maintain this project based on feedback. New features? Probably, do you have any suggestions?

**Comment by TeaqariaWTF** [comment]
I just started using it and it works fine for me now I don't know what kind of features can be added
